#!/usr/bin/env python
"""Build Cython extensions for the gridstate package (optional packaging tool).

Compiles every package .py file to .pyd (Windows) / .so (Linux), except files
incompatible with Cython (see SKIP_NAMES).

Usage:
    python build_cython.py              # compile alongside the .py files
    python build_cython.py --remove-py  # remove .py after compiling (for distribution)
"""

import contextlib
import io
import os
import re
import shutil
import sys
from concurrent.futures import ProcessPoolExecutor, as_completed
from pathlib import Path


REMOVE_PY = "--remove-py" in sys.argv

SKIP_NAMES = {
    "__init__.py",  # import machinery
    "_version.py",  # setuptools_scm autogenerated
}

# Files using @jit / jit(nopython=...) are incompatible with Cython: after
# compilation the function becomes a C function and numba cannot decorate it.
_NUMBA_JIT_RE = re.compile(r"@jit\(|=\s*jit\(nopython")


def _has_inline_numba_jit(path: Path) -> bool:
    try:
        return bool(_NUMBA_JIT_RE.search(path.read_text(encoding="utf-8", errors="ignore")))
    except OSError:
        return False


def _should_skip(path: Path) -> bool:
    if path.name in SKIP_NAMES:
        return True
    return bool(_has_inline_numba_jit(path))


def _module_name(py_file: Path, package_dir: Path) -> str:
    rel = py_file.relative_to(package_dir.parent)
    return rel.with_suffix("").as_posix().replace("/", ".")


def _is_windows() -> bool:
    return sys.platform == "win32"


def _using_mingw() -> bool:
    return _is_windows() and not shutil.which("cl") and bool(shutil.which("gcc"))


def _get_compiler_args() -> list[str]:
    if not _is_windows():
        return []
    if shutil.which("cl"):
        return []
    if shutil.which("gcc"):
        print("INFO: MSVC not found, using MinGW (gcc)")
        return ["--compiler=mingw32"]
    return []


def _compile_one_worker(task: tuple) -> tuple[str, bool, str]:
    """Runs in a separate process. Returns (path, ok, error_output)."""
    py_file_str, module_name, numpy_include, extra_compile_args, compiler_args = task
    from Cython.Build import cythonize
    from setuptools import Extension, setup

    ext = Extension(
        module_name,
        sources=[py_file_str],
        include_dirs=[numpy_include],
        extra_compile_args=extra_compile_args,
    )
    buf = io.StringIO()
    try:
        with contextlib.redirect_stdout(buf), contextlib.redirect_stderr(buf):
            setup(
                ext_modules=cythonize(
                    [ext],
                    compiler_directives={"language_level": "3", "annotation_typing": False},
                    quiet=True,
                ),
                script_args=["build_ext", "--inplace", *compiler_args],
            )
        return (py_file_str, True, "")
    except (Exception, SystemExit) as e:
        # A C compiler error in setup() raises SystemExit, not Exception — catch
        # both so the whole pool is not torn down. Files that fail to build stay
        # as .py.
        return (py_file_str, False, buf.getvalue() + "\n" + str(e))


def build() -> None:
    try:
        import numpy
    except ImportError as e:
        print(f"ERROR: Missing dependency: {e}")
        print("Install with: pip install cython numpy setuptools")
        sys.exit(1)

    project_root = Path(__file__).parent
    pkg_dir = project_root / "gridstate"

    all_py = sorted(pkg_dir.rglob("*.py"))
    skipped = [f.name for f in all_py if _should_skip(f)]
    to_compile = [f for f in all_py if not _should_skip(f)]

    # -DMS_WIN64: needed for MinGW so the Python headers set SIZEOF_VOID_P=8.
    extra_compile_args = ["-DMS_WIN64"] if _using_mingw() else []
    compiler_args = _get_compiler_args()
    numpy_include = numpy.get_include()

    nworkers = os.cpu_count() or 1
    print(f"Found {len(all_py)} .py files total")
    print(f"Skipping {len(skipped)}: {skipped}")
    print(f"\nCompiling {len(to_compile)} modules with Cython (workers={nworkers})...\n")

    tasks = [
        (str(f), _module_name(f, pkg_dir), numpy_include, extra_compile_args, compiler_args)
        for f in to_compile
    ]

    compiled: list[Path] = []
    failed: list[str] = []

    try:
        with ProcessPoolExecutor(max_workers=nworkers) as executor:
            futures = {executor.submit(_compile_one_worker, t): t for t in tasks}
            for future in as_completed(futures):
                py_file_str, ok, err = future.result()
                py_file = Path(py_file_str)
                rel = py_file.relative_to(pkg_dir)
                if ok:
                    print(f"  OK: {rel}")
                    compiled.append(py_file)
                else:
                    print(f"  FAIL: {rel}")
                    for line in err.strip().splitlines()[-10:]:
                        print(f"       {line}")
                    failed.append(py_file.name)
    finally:
        _cleanup(project_root, pkg_dir)

    print(f"\nCompiled: {len(compiled)}/{len(to_compile)}")
    if failed:
        print(f"Failed (kept as bytecode): {failed}")

    _strip_binaries(pkg_dir)

    if REMOVE_PY:
        _remove_py_files(compiled)
    else:
        print("\nSource .py files kept. Use --remove-py to remove them for distribution.")


def _strip_binaries(pkg_dir: Path) -> None:
    """Strip debug symbols from the compiled extensions.

    Linux/macOS: strip --strip-debug *.so
    Windows MSVC: removes *.pdb
    Windows MinGW: strip --strip-debug *.pyd
    """
    stripped = 0

    if _is_windows():
        for pdb in pkg_dir.rglob("*.pdb"):
            pdb.unlink()
            stripped += 1
        if stripped:
            print(f"Stripped: removed {stripped} .pdb files (MSVC debug info)")

        if _using_mingw() and shutil.which("strip"):
            import subprocess

            for pyd in pkg_dir.rglob("*.pyd"):
                result = subprocess.run(["strip", "--strip-debug", str(pyd)], capture_output=True)
                if result.returncode == 0:
                    stripped += 1
                else:
                    print(f"  WARNING: strip failed for {pyd.name}: {result.stderr.decode()}")
            print(f"Stripped: {stripped} .pyd files (MinGW debug symbols removed)")
    else:
        strip_cmd = shutil.which("strip")
        if not strip_cmd:
            print("WARNING: strip not found, skipping debug symbol removal")
            return
        import subprocess

        for so in pkg_dir.rglob("*.so"):
            result = subprocess.run([strip_cmd, "--strip-debug", str(so)], capture_output=True)
            if result.returncode == 0:
                stripped += 1
            else:
                print(f"  WARNING: strip failed for {so.name}: {result.stderr.decode()}")
        print(f"Stripped: {stripped} .so files (debug symbols removed)")


def _cleanup(project_root: Path, pkg_dir: Path) -> None:
    build_dir = project_root / "build"
    if build_dir.exists():
        shutil.rmtree(build_dir)
        print("Removed: build/")
    for c_file in pkg_dir.rglob("*.c"):
        c_file.unlink()
        print(f"Removed: {c_file.relative_to(pkg_dir)}")


def _remove_py_files(compiled: list[Path]) -> None:
    print("\nRemoving source .py files for distribution...")
    removed = 0
    not_found = []
    for py_file in compiled:
        pyd = list(py_file.parent.glob(f"{py_file.stem}*.pyd"))
        so = list(py_file.parent.glob(f"{py_file.stem}*.so"))
        if pyd or so:
            py_file.unlink()
            removed += 1
        else:
            print(f"  WARNING: No .pyd/.so for {py_file.name} — kept as bytecode")
            not_found.append(py_file.name)
    print(f"\nRemoved {removed} source files.")
    if not_found:
        print(f"WARNING: {len(not_found)} files kept as bytecode: {not_found}")


if __name__ == "__main__":
    build()
